#!/bin/bash

# Setup local development environment for Supabase
# This script starts Supabase and creates/updates .env.local with the correct keys

set -e

echo "Starting Supabase local development environment..."

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "Error: Docker is not running. Please start Docker and try again."
    exit 1
fi

# Start Supabase (if not already running)
echo "Starting Supabase..."
npx supabase start

# Get the status and extract keys
echo ""
echo "Extracting Supabase credentials..."

STATUS=$(npx supabase status)

# Extract the anon key and API URL
ANON_KEY=$(echo "$STATUS" | grep "anon key:" | awk '{print $3}')
API_URL=$(echo "$STATUS" | grep "API URL:" | awk '{print $3}')

if [ -z "$ANON_KEY" ] || [ -z "$API_URL" ]; then
    echo "Error: Could not extract Supabase credentials. Run 'npx supabase status' manually."
    exit 1
fi

# Create or update .env.local
ENV_LOCAL_FILE=".env.local"

echo "Writing credentials to $ENV_LOCAL_FILE..."

cat > "$ENV_LOCAL_FILE" << EOF
# Local Supabase Development Environment
# Generated by scripts/setup-local-env.sh
# DO NOT COMMIT THIS FILE

VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo ""
echo "✅ Local environment configured successfully!"
echo ""
echo "Supabase services are now running:"
echo "  - API URL: $API_URL"
echo "  - Studio:  http://127.0.0.1:54323 (Database admin UI)"
echo "  - Inbucket: http://127.0.0.1:54324 (Email testing)"
echo ""
echo "Commands:"
echo "  npm run dev        - Start Vite dev server (uses local Supabase)"
echo "  npm run db:reset   - Reset local DB and run all migrations"
echo "  npm run db:stop    - Stop Supabase containers"
echo "  npm run db:push    - Push migrations to production"
echo ""
